name: Build & Push Docker Image

on:
  push:
    branches:
      - main

env:
  PROJECT_NAME: Vicgital.HtmlToPdfGenerator.Service
  BUILD_CONFIGURATION: Release
  IMAGE_REPOSITORY: vicgital/vicgital.htmltopdfgenerator.service
  DOCKERFILE_PATH: ./Dockerfile

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Set up NuGet authentication for Azure Artifacts
        run: |
          echo "NUGET_AUTH_TOKEN=${{ secrets.AZURE_DEVOPS_PAT }}" >> $GITHUB_ENV

      - name: Restore dependencies
        run: dotnet restore ./src/${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj --configfile nuget.config

      - name: Publish .NET project
        run: dotnet publish ./src/${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj --configuration ${{ env.BUILD_CONFIGURATION }} --output ./output

      - name: Copy Dockerfile to output directory
        run: cp ${{ env.DOCKERFILE_PATH }} ./output/

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./output
          file: ./output/Dockerfile
          push: true
          tags: ${{ env.IMAGE_REPOSITORY }}:main-${{ github.sha }}
